apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.apigeeTokenSecret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  APIGEE_TOKEN: {{ .Values.apigeeTokenSecret.token | quote }}
