apiVersion: v1
kind: ConfigMap
metadata:
  name: credentialsmanagement-operator-configmap
  labels:
    {{- include "credentialsmanagement-operator.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  LOGGING: {{ .Values.configmap.loglevel | quote }}
  KEYCLOAK_BASE: "{{ .Values.configmap.kcbase }}"
  KEYCLOAK_REALM: "{{ .Values.configmap.kcrealm }}"
  COMPONENT_NAMESPACE: "{{ .Values.deployment.monitoredNamespaces }}"

