apiVersion: v1
kind: Secret
metadata:
  name: credentialsmanagement-operator-secret
  labels:
    {{- include "credentialsmanagement-operator.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  CLIENT_ID: {{ .Values.credentials.client_id | b64enc | quote }}
  CLIENT_SECRET: {{ .Values.credentials.client_secret | b64enc | quote }}